spring.config.import=file:backend/.env.properties
spring.application.name=dealership-app-api
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
server.address=0.0.0.0
management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=health,metrics